# What is NumPy
NumPy (Numerical Python) is a powerful Python library used for numerical and scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

Key features include:
- **Efficient Array Operations**: Enables fast operations on arrays, such as element-wise calculations, broadcasting, and linear algebra functions.
- **Integration**: Works seamlessly with other scientific libraries like Pandas, SciPy, and Matplotlib.
- **Vectorization**: Allows computations to be written in a concise and efficient way, avoiding slow Python loops.

NumPy is essential for handling numerical data in machine learning and data science tasks.

> *Just this is not Enough. Thus, I would say that taking reference from the documentation is something that I would highly recommend. Thus, below is the link for the documentation of the same:-*
**https://docs.scipy.org/doc/numpy/reference/routines.linalg.html**







**THE FOLLOWING IS A FILE THAT WILL BE TEACHING HOW TO USE NUMPY AND ALL THE THINGS THAT FOLLOW**

In [2]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
print(a)

# this is where we made an array using numpy

# b=np.array([[1,2,3,4,5,6], [3.0, 41.0]])
# print(b)
# the above line shows error because in numpy, we need it to be of equal mxn


b=np.array([[1,2,3], [1.324, 23.453, 1.0]])
print(b)

# to get the dimensions of the numpy array, we do:-
print("The Dimensions are:- ",b.ndim)    # its like, <arrayName>.ndim

[1 2 3]
[[ 1.     2.     3.   ]
 [ 1.324 23.453  1.   ]]
The Dimensions are:-  2


The SHAPE thing in Numpy

In [ ]:
# there is one more thing called as Shape of the array
print("Shape of A:- ", a.shape) # since A is 1D array of 3 columns
print("Shape of B:- ", b.shape) # since B is 2D array of 2rows, 3columns

Shape of A:-  (3,)
Shape of B:-  (2, 3)


In [ ]:
# we can even get the Memory that it is taking and other related things
print("Data Type of array a", a.dtype)  # we are getting the data-type of array "a"

'''
So, we can use a specific datatype and memory if needed
Like, If I know that the array is going to store low valued data
I can specif to use less memory.
See below:-
'''
something=np.array([1,2,3,4,5,6,7], dtype='int16')
print(something, " has the data type of ", something.dtype)

int64
[1 2 3 4 5 6 7]  has the data type of  int16


# ACCCESSING/CHANGING SPECIFIC ELEMENTS, ROWS, COLUMNS

In [ ]:
a=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# to get a specific element, we do the following:-
print(a[1,2]);  # syntax is as:- [row, col]
# NOTE:- it is Zero Indexing in Python as well
# we start the matrix as:-
'''
    0 1 2 3 . . .
0   x y z e
1   a b c d . . .
2   .
3   .
'''

# print(a[2,3]) this would throw an error as it is out of bounds

8


'\n    0 1 2 3 . . . \n0   x y z e\n1   a b c d . . . \n2   .\n3   .    \n'

In [ ]:
# TO GET A SPECIFIC ROW- WE DO THE FOLLOWING:-

print("The First row of the matrix is:- ", a[0,])

print("And the First Column is:- ", a[:,0]) # this is the syntax for column

The First row of the matrix is:-  [1 2 3 4 5]
And the First Column is:-  [1 6]


In [ ]:
# now say, I wanna make the first element of the matrix, say 0,0 to 99, we do:-

a[0,0]=99   # TO CHANGE THE 0,0th Index
print(a,"\n")

# a[0,]=54    # TO MAKE THE WHOLE ROW AS A NUMBER(here, 54)
# print(a)

[[99 54 54 54 54]
 [ 6  7  8  9 10]] 



In [ ]:
# for getting something similar as Substring, we do this:-
# <variableName> [startIndex:endIndex:stepSize]

a1=np.array([ [1,2,3,4,5,6], [11,12,13,14,15,16]])
print(a1)
print(a1[1,1:3:1])  # this is as:- [x,y : ind : steps]

# where (x,y) is position in the MATRIX
#       ind is the index till where it should go linearly
#       steps is the number of indexes to jump for printing

[[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]]
[12 13]


In [ ]:
# this is an example of a 3D Matrix
d=np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(d)

# so, the first thing is indexed zero
# within 0, there are two arrays that are of 1,2 and 3,4
# they are indexed 0, 1 respectively
# And within that, there is 0,1 present

print(d[0,1,0]) # this means, we want to access the bigger array 0
                # then, we want to access the 2nd sub array, and its 1st one

# we can even play around something like this:-
print(d[: , 1, :])
# this means, (:) -> don't care what number, in short, both/all

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
[[3 4]
 [7 8]]


# INITIALIZING DIFFERENT TYPES OF ARRAYS

In [ ]:
# To make all zeroes
np.zeros((2,3))   # NOTE:- np is not variable, but for numpy instance we gave above

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Making a Unit Matrix
print(np.ones((3,3)))

# We can even enter out own data type
oness=np.ones((3,3), dtype='int8')
print(oness, "which is of DATATYPE ", oness.dtype)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]] which is of DATATYPE  int8


In [ ]:
# We can fill the whole matrix with a REQUIRED NUMBER THAT WE WANT
np.full((3,3), 98)

array([[98, 98, 98],
       [98, 98, 98],
       [98, 98, 98]])

In [ ]:
# We can even add some random number in matrix as:-

print(np.random.rand(3,5))
print("\n")

# we want random integers that are less than 7, in a matrix of 3x3
np.random.randint(7, size=(3,3))

# There is something like this as well:-
print(np.random.randint(1,9, size=(4,2)))

[[0.41071781 0.77344481 0.83753528 0.17317714 0.05908834]
 [0.20067499 0.35495135 0.12370757 0.02478193 0.85078352]
 [0.32841348 0.43074539 0.86118803 0.14892996 0.30779904]]


[[4 1]
 [6 4]
 [6 4]
 [3 7]]


In [ ]:
# We can even have an identity matrix(diagonal 1) here which goes by the syntax:-
np.identity(3, dtype='int8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [ ]:
# We can even repeat the same pattern in the matrix as follows:-

arr=np.array([[1,2,3]])
r1=np.repeat(arr, 3, axis=0)

print(r1)
# so the command bascially says we repeat the array "arr"
# it is repeated 3 times, and repeat along the 0th axis
# that is, repeat the whole 1st array over 3 times in diff rows


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# NOW let us try to make an array such that, the outer line is all one
# the next inner layer is of all 0s
# and then, 9s as the innermost

answer=np.ones((5,5), dtype='int16')
print(answer)

z=np.zeros((3,3))
z[1,1]=9
print("\n\n")
answer[1:4 , 1:4]=z
print("The Output is:-\n", answer)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]



The Output is:-
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]




> THIS IS REALLY IMPORTANT TO NOTE- When we directly equate 2(or more) Matrices, they are Equated Via  `pass by reference`



In [ ]:
# Suppose, we do the following:-

a=np.identity(4, dtype='int8')
print("So, Matrix A looks like:-\n",a)
b=a
print("And, when we say B=A, B looks like:-\n", b)

# NOW COMES THE THING. If I want to make the value at position (0,1)=99
# See what happens
b[(0,1)]=99
print(a)
print("\n")
print(b)

# b thus, did not make any copy of a, but rather, referenced a
# so a better way is:-
c=a.copy()

c[(0,1)]=0
print('MAKING c as COPY OF a, WE SEE:-\n')
print(a,"\n",b,"\n",c)

So, Matrix A looks like:-
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
And, when we say B=A, B looks like:-
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[ 1 99  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]]


[[ 1 99  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]]
MAKING c as COPY OF a, WE SEE:-

[[ 1 99  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]] 
 [[ 1 99  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]] 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# MATHEMATICS PART

In [ ]:
# this is the section where we do some Mathematics on Arrays and its members

peeps=np.array([1,2,3,4,5])
print(peeps)

[1 2 3 4 5]


In [ ]:
peeps+2   # the logic being, we add each and every element by 2

array([3, 4, 5, 6, 7])

In [ ]:
peeps*12  # we do not alter 3,4,... but rather original 'peeps'

array([12, 24, 36, 48, 60])

In [ ]:
b=np.array([2,3,4,51,7])
print(peeps+b)

print(b**2)

[ 3  5  7 55 12]
[   4    9   16 2601   49]


#### LINEAR ALGEBRA

In [4]:
# Now, we learn some LINEAR ALGEBRA IN NumPy
a=np.ones((2,3))
b=np.full((3,2), 2)

# c=a*b this does not work in numpy, thus we do:-
np.matmul(a,b)  # matmul means, Mathematical Multiplication

# NOTE:- This worked because C1=R2 for the given matrices (Column of 1st should be Rows of 2nd)


array([[6., 6.],
       [6., 6.]])

In [ ]:
# We can even get the determinant of the matrix as follows:-
matri=np.identity(3)
np.linalg.det(matri)    # this is equal to- np.LinearAlgebra.Determinant

# For more such, refer to the below link:-
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

### STATISTICS

In [17]:
stats=np.array([[1,2,3], [4,5,6]])
stats

# TO FIND THE MINIMUM, WE DO:-
np.min(stats)

# TO FIND THE MAXIMUM, WE DO:-
np.max(stats)

# FOR GETTING THE SUM:-
np.sum(stats)
print("Sum along the AXIS-0 => adding vertically ",np.sum(stats, axis=0))
print("Sum along the AXIS-1 => adding horizontally ",np.sum(stats, axis=1))



Sum along the AXIS-0 => adding vertically  [5 7 9]
Sum along the AXIS-1 => adding horizontally  [ 6 15]


### REORGANIZING THE ARRAYS

In [24]:
before=np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after=before.reshape((8,1))
print(after)

after2=before.reshape((1,8))
print(after2)

# NOTE:- We can go to any reshape till we observe- totalElements=row*col

# VERTICALLY STACKING OF VECTORS
v1=np.array([1,2,3,4,5])
v2=np.array([6,7,8,9,10])

print("\n")
np.vstack([v1, v2])   # Stacks the vectors each over the other

# v11=np.array([1,2,3,4,5,6,7,8,9])
# v12=np.array([12,13,14])

# np.vstack([v11, v12])

# the above is something that cannot happen because they are not of same dimensions

np.hstack([v1,v2])    # this leads to horizontal stack

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4 5 6 7 8]]




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### SOME MISCELLANEOUS THINGS

In [27]:
# NOW, WE CAN LOAD SOME DATA FROM THE FILE.
# The File will be available on the GitHub Page-so do refer to that for the same
# Like, I would say, upload the file here-in the Colab
# And then use it

fileData=np.genfromtxt('data.txt', delimiter=',')

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

### BOOLEAN MASKING and ADVANCED INDEXING

In [34]:
fileData=np.genfromtxt('data.txt', delimiter=',')

boolFile=fileData>50
boolFile
# this is something that would return true or false
#  based on each and every array value

# also, we can get those specific indices where it is greater than a specific val

fileData[fileData > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

### We can INDEX with a List in NumPy

In [36]:
a=np.array([1,2,3,4,5,6,7,8,9])
a[[0,1,5]]

# if u notice, I entered a list in the a[]
# like, [0,1,5] are the members of the list
# and then, when we passed this on to a[] itself, we used members as index

array([1, 2, 6])

# A CASE STUDY (quick recap)

In [48]:
# Suppose, we have the following array present-how will we access the following:-

arr=np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25],
             [26,27,28,29,30]])

'''
NOW ACCESS THE THINGS ASKED BELOW:-
1) Access 11,12,16,17
2) Access 2,8,14,20
3) Access 4,5,29,30, 24,25
'''

# for 1:-
print("\nAnswer 1: \n",arr[2:4, 0:2])

# for 2:-
print("\nAnswer 2:-\n", arr[[0,1,2,3], [1,2,3,4]])

# for 3:-
print("\nAnswer 3:-\n", arr[[0,4,5], 3:])


Answer 1: 
 [[11 12]
 [16 17]]

Answer 2:-
 [ 2  8 14 20]

Answer 3:-
 [[ 4  5]
 [24 25]
 [29 30]]
